config/routes.rb
Rails.application.routes.draw do
  resources :bgroups
  resources :bgroups
  resources :centers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :branch_managers
  resources :donors
  get 'welcome/index'

   root 'welcome#index'

end

app/models/bgroup.rb
class Bgroup < ActiveRecord::Base
  belongs_to :center
end

app/controllers/bgroups_controller.rb
class BgroupsController < ApplicationController
  before_action :set_bgroup, only: [:show, :edit, :update, :destroy]

  # GET /bgroups
  # GET /bgroups.json
  def index
    @bgroups = Bgroup.all
  end

  # GET /bgroups/1
  # GET /bgroups/1.json
  def show
  end

  # GET /bgroups/new
  def new
    @bgroup = Bgroup.new
  end

  # GET /bgroups/1/edit
  def edit
  end

  # POST /bgroups
  # POST /bgroups.json
  def create
    @bgroup = Bgroup.new(bgroup_params)

    respond_to do |format|
      if @bgroup.save
        format.html { redirect_to @bgroup, notice: 'Bgroup was successfully created.' }
        format.json { render :show, status: :created, location: @bgroup }
      else
        format.html { render :new }
        format.json { render json: @bgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bgroups/1
  # PATCH/PUT /bgroups/1.json
  def update
    respond_to do |format|
      if @bgroup.update(bgroup_params)
        format.html { redirect_to @bgroup, notice: 'Bgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @bgroup }
      else
        format.html { render :edit }
        format.json { render json: @bgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bgroups/1
  # DELETE /bgroups/1.json
  def destroy
    @bgroup.destroy
    respond_to do |format|
      format.html { redirect_to bgroups_url, notice: 'Bgroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bgroup
      @bgroup = Bgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bgroup_params
      params.require(:bgroup).permit(:a_positive, :b_positive, :o_positive, :ab_positive, :a_negative, :b_negative, :o_negative, :ab_negative, :center_id)
    end
end

app/helpers/bgroups_helper.rb
module BgroupsHelper
end

app/views/bgroups/_form.html.erb
<%= form_for(@bgroup) do |f| %>
  <% if @bgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bgroup.errors.count, "error") %> prohibited this bgroup from being saved:</h2>

      <ul>
      <% @bgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a_positive %><br>
    <%= f.number_field :a_positive %>
  </div>
  <div class="field">
    <%= f.label :b_positive %><br>
    <%= f.number_field :b_positive %>
  </div>
  <div class="field">
    <%= f.label :o_positive %><br>
    <%= f.number_field :o_positive %>
  </div>
  <div class="field">
    <%= f.label :ab_positive %><br>
    <%= f.number_field :ab_positive %>
  </div>
  <div class="field">
    <%= f.label :a_negative %><br>
    <%= f.number_field :a_negative %>
  </div>
  <div class="field">
    <%= f.label :b_negative %><br>
    <%= f.number_field :b_negative %>
  </div>
  <div class="field">
    <%= f.label :o_negative %><br>
    <%= f.number_field :o_negative %>
  </div>
  <div class="field">
    <%= f.label :ab_negative %><br>
    <%= f.number_field :ab_negative %>
  </div>
  <div class="field">
    <%= f.label :center_id %><br>
    <%= f.text_field :center_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bgroups/edit.html.erb
<h1>Editing Bgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @bgroup %> |
<%= link_to 'Back', bgroups_path %>

app/views/bgroups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bgroups</h1>

<table>
  <thead>
    <tr>
      <th>A positive</th>
      <th>B positive</th>
      <th>O positive</th>
      <th>Ab positive</th>
      <th>A negative</th>
      <th>B negative</th>
      <th>O negative</th>
      <th>Ab negative</th>
      <th>Center</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bgroups.each do |bgroup| %>
      <tr>
        <td><%= bgroup.a_positive %></td>
        <td><%= bgroup.b_positive %></td>
        <td><%= bgroup.o_positive %></td>
        <td><%= bgroup.ab_positive %></td>
        <td><%= bgroup.a_negative %></td>
        <td><%= bgroup.b_negative %></td>
        <td><%= bgroup.o_negative %></td>
        <td><%= bgroup.ab_negative %></td>
        <td><%= bgroup.center %></td>
        <td><%= link_to 'Show', bgroup %></td>
        <td><%= link_to 'Edit', edit_bgroup_path(bgroup) %></td>
        <td><%= link_to 'Destroy', bgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bgroup', new_bgroup_path %>

app/views/bgroups/new.html.erb
<h1>New Bgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', bgroups_path %>

app/views/bgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A positive:</strong>
  <%= @bgroup.a_positive %>
</p>

<p>
  <strong>B positive:</strong>
  <%= @bgroup.b_positive %>
</p>

<p>
  <strong>O positive:</strong>
  <%= @bgroup.o_positive %>
</p>

<p>
  <strong>Ab positive:</strong>
  <%= @bgroup.ab_positive %>
</p>

<p>
  <strong>A negative:</strong>
  <%= @bgroup.a_negative %>
</p>

<p>
  <strong>B negative:</strong>
  <%= @bgroup.b_negative %>
</p>

<p>
  <strong>O negative:</strong>
  <%= @bgroup.o_negative %>
</p>

<p>
  <strong>Ab negative:</strong>
  <%= @bgroup.ab_negative %>
</p>

<p>
  <strong>Center:</strong>
  <%= @bgroup.center %>
</p>

<%= link_to 'Edit', edit_bgroup_path(@bgroup) %> |
<%= link_to 'Back', bgroups_path %>