config/routes.rb
Rails.application.routes.draw do
  resources :bgroups
  resources :bgroups
  resources :centers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :branch_managers
  resources :donors
  get 'welcome/index'

   root 'welcome#index'

end

app/models/center.rb
class Center < ActiveRecord::Base
	has_many :bgroups, dependent: :destroy
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: [:show, :edit, :update, :destroy]

  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all
  end

  # GET /centers/1
  # GET /centers/1.json
  def show
  end

  # GET /centers/new
  def new
    @center = Center.new
  end

  # GET /centers/1/edit
  def edit
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(center_params)

    respond_to do |format|
      if @center.save
        format.html { redirect_to @center, notice: 'Center was successfully created.' }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centers/1
  # PATCH/PUT /centers/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)
        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center.destroy
    respond_to do |format|
      format.html { redirect_to centers_url, notice: 'Center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def center_params
      params.require(:center).permit(:name, :address)
    end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.erb
<%= form_for(@center) do |f| %>
  <% if @center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@center.errors.count, "error") %> prohibited this center from being saved:</h2>

      <ul>
      <% @center.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/centers/edit.html.erb
<h1>Editing Center</h1>

<%= render 'form' %>

<%= link_to 'Show', @center %> |
<%= link_to 'Back', centers_path %>

app/views/centers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Centers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centers.each do |center| %>
      <tr>
        <td><%= center.name %></td>
        <td><%= center.address %></td>
        <td><%= link_to 'Show', center %></td>
        <td><%= link_to 'Edit', edit_center_path(center) %></td>
        <td><%= link_to 'Destroy', center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Center', new_center_path %>

app/views/centers/new.html.erb
<h1>New Center</h1>

<%= render 'form' %>

<%= link_to 'Back', centers_path %>

app/views/centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @center.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @center.address %>
</p>

<%= link_to 'Edit', edit_center_path(@center) %> |
<%= link_to 'Back', centers_path %>