config/routes.rb
Rails.application.routes.draw do
  resources :bgroups
  resources :bgroups
  resources :centers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :branch_managers
  resources :donors
  get 'welcome/index'

   root 'welcome#index'

end

app/models/branch_manager.rb
class BranchManager < User
end

app/controllers/branch_managers_controller.rb
class BranchManagersController < ApplicationController
  before_action :set_branch_manager, only: [:show, :edit, :update, :destroy]

  # GET /branch_managers
  # GET /branch_managers.json
  def index
    @branch_managers = BranchManager.all
  end

  # GET /branch_managers/1
  # GET /branch_managers/1.json
  def show
  end

  # GET /branch_managers/new
  def new
    @branch_manager = BranchManager.new
  end

  # GET /branch_managers/1/edit
  def edit
  end

  # POST /branch_managers
  # POST /branch_managers.json
  def create
    @branch_manager = BranchManager.new(branch_manager_params)

    respond_to do |format|
      if @branch_manager.save
        format.html { redirect_to @branch_manager, notice: 'Branch manager was successfully created.' }
        format.json { render :show, status: :created, location: @branch_manager }
      else
        format.html { render :new }
        format.json { render json: @branch_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branch_managers/1
  # PATCH/PUT /branch_managers/1.json
  def update
    respond_to do |format|
      if @branch_manager.update(branch_manager_params)
        format.html { redirect_to @branch_manager, notice: 'Branch manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch_manager }
      else
        format.html { render :edit }
        format.json { render json: @branch_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branch_managers/1
  # DELETE /branch_managers/1.json
  def destroy
    @branch_manager.destroy
    respond_to do |format|
      format.html { redirect_to branch_managers_url, notice: 'Branch manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch_manager
      @branch_manager = BranchManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_manager_params
      params.require(:branch_manager).permit(:name)
    end
end

app/helpers/branch_managers_helper.rb
module BranchManagersHelper
end

app/views/branch_managers/_form.html.erb
<%= form_for(@branch_manager) do |f| %>
  <% if @branch_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch_manager.errors.count, "error") %> prohibited this branch_manager from being saved:</h2>

      <ul>
      <% @branch_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branch_managers/edit.html.erb
<h1>Editing Branch Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch_manager %> |
<%= link_to 'Back', branch_managers_path %>

app/views/branch_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Branch Managers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branch_managers.each do |branch_manager| %>
      <tr>
        <td><%= branch_manager.name %></td>
        <td><%= link_to 'Show', branch_manager %></td>
        <td><%= link_to 'Edit', edit_branch_manager_path(branch_manager) %></td>
        <td><%= link_to 'Destroy', branch_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch manager', new_branch_manager_path %>

app/views/branch_managers/new.html.erb
<h1>New Branch Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', branch_managers_path %>

app/views/branch_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch_manager.name %>
</p>

<%= link_to 'Edit', edit_branch_manager_path(@branch_manager) %> |
<%= link_to 'Back', branch_managers_path %>